// src/ui/Collection/Collection.tsx
import React, { useEffect, useState } from 'react';
import { GameDto, GamesGroupDto, GamingInterface } from '../../services';
import { setActiveTabTitle } from '../../utils';
import { Page } from './Page';
import { CollectionOptions } from './Collection.types';

export interface CollectionProps {
    gaming: GamingInterface;
    path: string;
    options?: CollectionOptions;
}

export const Collection = ({ gaming, path, options }: CollectionProps) => {
    const [search, setSearch] = useState('');

    const searchRegExp = new RegExp(search, 'i');

    const filter = search
        ? (game: GameDto) => !!game.title.match(searchRegExp)
        : undefined;

    const localStorageGroupedParam = `${path}:grouped`;

    const [grouped, setGrouped] = useState(false);

    useEffect(() => {
        const localStorageGrouped = JSON.parse(
            localStorage.getItem(localStorageGroupedParam),
        );

        if (localStorageGrouped !== undefined) {
            setGrouped(localStorageGrouped);
        }
    }, []);

    useEffect(() => {
        localStorage.setItem(localStorageGroupedParam, JSON.stringify(grouped));
    }, [grouped]);

    const sort = (game: GameDto) => [game.status, game.title];

    const collection = gaming.getCollection(path);

    const games = grouped
        ? undefined
        : (gaming.getGames(path, filter, sort) as GameDto[]);

    const gamesGroups = grouped
        ? (gaming.getGames(
            path,
            filter,
            sort,
            (game: GameDto) => game.platforms[0],
            (group: GamesGroupDto) => -1 * group.games.length,
        ) as GamesGroupDto[])
        : undefined;

    setActiveTabTitle(document, collection.title);

    return (
        <Page
            collection={collection}
            games={games}
            gamesGroups={gamesGroups}
            search={search}
            onSearchChange={(value) => setSearch(value)}
            grouped={grouped}
            onGroupedChange={(value) => setGrouped(value)}
            options={options}
        />
    );
};

// src/ui/Collection.svelte
<script lang="ts">
    import type { CollectionOptions } from "../types/ui";
    import type { GameDto, GamesGroupDto, PlatformDto } from "../types/gaming";
    import Gaming from "../service/Gaming";
    import { setActiveTabTitle } from "../service/ObsidianUtils";
    import CollectionPage from "./collection/CollectionPage.svelte";

    export let initialized: boolean = false;
    export let sourcePath: string;
    export let gaming: Gaming;
    export let options: CollectionOptions = {};

    let search = '';

    $: searchRegExp = new RegExp(search, 'i')

    $: filter = search ? (game: GameDto) => !!game.title.match(searchRegExp): undefined

    const localStorageGroupedParam = `${sourcePath}:grouped`;

    let grouped = !!JSON.parse(localStorage.getItem(localStorageGroupedParam) ?? 'false');

    $: localStorage.setItem(localStorageGroupedParam, JSON.stringify(grouped));

    const sort = (game: GameDto) => ([game.status?.order, game.title])

    $: collection = initialized
        ? gaming.getCollection(sourcePath)
        : undefined

    $: games = initialized && !grouped
        ? gaming.getGames(sourcePath, filter, sort) as GameDto[]
        : undefined;

    $: gamesGroups = initialized && grouped
        ? gaming.getGames(
            sourcePath,
            filter,
            sort,
            (game: GameDto) => game.platforms[0],
            (group: { id: PlatformDto }) => group.id.order,
        ) as GamesGroupDto[]
        : undefined;

    $: if (collection) {
        setActiveTabTitle(document, collection.title);
    }

</script>

{ #if initialized && collection }
    <CollectionPage
        collection={ collection }
        games={ games }
        gamesGroups={ gamesGroups }
        bind:search={ search }
        bind:grouped={ grouped }
        options={ options }
    />
{ :else }
    <span>Loading...</span>
{ /if }
