// src/ui/Rating.svelte
<script lang="ts">
    import LucideIcon from "./common/LucideIcon.svelte";

    export let rating: number;
</script>

<span class="container">
    { #each [1, 2, 3, 4, 5] as index }
        { #if rating >= index }
            <LucideIcon name="Star" fill="gold" color="gold" size=16 />
        { :else if rating > (index - 1) }
            <LucideIcon name="Star" color="gold" size=16 />
        { :else }
            <LucideIcon name="Star" size=16 />
        { /if }
    { /each }
</span>

<style>
    span.container {
        display: flex;
        align-items: center;
    }
</style>

// src/ui/Rating/Rating.tsx
import React from 'react';
import { Star } from 'lucide-react';
import './Rating.css';

export interface RatingProps {
    rating: number;
    size?: number;
}

export const Rating = ({ rating, size = 16 }: RatingProps) => (
    <span className="rating">
        {[1, 2, 3, 4, 5].map((index) => {
            if (rating >= index) {
                return (
                    <Star
                        key={index}
                        fill="gold"
                        color="gold"
                        size={size}
                    />
                );
            }

            if (rating > index - 1) {
                return <Star key={index} color="gold" size={size} />;
            }

            return <Star key={index} size={size} />;
        })}
    </span>
);
